import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createProcessor} from '../supabase/functions/_shared/pipeline.js';
import {Resvg,initWasm} from '@resvg/resvg-wasm';
import {cardSvg} from '../supabase/functions/_shared/card.js';
import {readFile} from 'node:fs/promises';
const today=new Date().toISOString().slice(0,10);
const settings={timezone:'UTC',automation_enabled:true,template_name:'birthday_greeting',template_language:'en_US',business_name:'Example',owner_name:'Alex',greeting_text:'Happy Birthday, {{name}}!'};
let initialized;
function harness({outcome='success',consent=true,storageFailure=false}={}){
 const row={id:'test-id',client_id:'client-id',client_name:'Michael',phone:'+12025550123',birthday_year:Number(today.slice(0,4)),kind:'birthday',status:'pending'};
 const client={id:'client-id',name:'Michael',phone:row.phone,birthday:today,active:true,whatsapp_consent:consent,last_birthday_sent_year:null};const uploads=new Map();let calls=0,payload;
 const db={from(table){let update,conditions=[];const query={update(value){update=value;return query;},select(){return query;},eq(k,v){conditions.push([k,v]);return query;},single(){return execute();},maybeSingle(){return execute();},then(resolve,reject){return execute().then(resolve,reject);}};async function execute(){const target=table==='clients'?client:row;if(conditions.some(([k,v])=>target[k]!==v))return {data:null,error:null};if(update)Object.assign(target,update);return {data:{...target},error:null};}return query;},storage:{from(bucket){assert.equal(bucket,'birthday-cards');return {async upload(path,png){if(storageFailure)return {error:new Error('Storage unavailable')};uploads.set(path,png);return {data:{path},error:null};},async createSignedUrl(path){assert.ok(uploads.has(path));return {data:{signedUrl:`https://storage.example/${path}?token=signed`},error:null};}};}},async rpc(name,params){assert.equal(name,'finish_message');row.status='sent';row.whatsapp_message_id=params.meta_id;client.last_birthday_sent_year=row.birthday_year;return {data:null,error:null};}};
 const process=createProcessor({db,check(result){if(result.error)throw result.error;return result.data;},required(name){return name==='META_GRAPH_VERSION'?'v23.0':'test-secret';},async renderCard(s,name){initialized??=readFile('supabase/functions/_shared/assets/index_bg.wasm').then(initWasm);await initialized;const renderer=new Resvg(cardSvg(s,name),{font:{fontBuffers:[await readFile('supabase/functions/_shared/assets/Inter.ttf')],loadSystemFonts:false}});try{return renderer.render().asPng();}finally{renderer.free();}},async fetch(url,options){calls++;assert.match(url,/^https:\/\/graph.facebook.com\/v23.0\//);payload=JSON.parse(options.body);if(outcome==='timeout')throw new Error('network timeout');if(outcome==='rejected')return Response.json({error:{message:'Template rejected'}},{status:400});return Response.json({messages:[{id:'wamid.mock-accepted'}]});}});
 return {row,client,uploads,process,get calls(){return calls;},get payload(){return payload;}};
}
test('complete pipeline: client → real PNG → simulated Storage → template → accepted → history; concurrent calls send once',async()=>{const h=harness();await Promise.all([h.process({...h.row},settings),h.process({...h.row},settings)]);assert.equal(h.calls,1);assert.equal(h.row.status,'sent');assert.equal(h.client.last_birthday_sent_year,Number(today.slice(0,4)));assert.equal(h.uploads.size,1);const png=[...h.uploads.values()][0];assert.deepEqual([...png.slice(0,4)],[137,80,78,71]);assert.equal(h.payload.template.components[1].parameters[0].text,'Michael');assert.match(h.payload.template.components[0].parameters[0].image.link,/token=signed/);});
test('revoked consent stops the send before rendering/upload',async()=>{const h=harness({consent:false});await h.process({...h.row},settings);assert.equal(h.calls,0);assert.equal(h.uploads.size,0);assert.equal(h.row.status,'failed');assert.equal(h.client.last_birthday_sent_year,null);});
test('confirmed rejection remains retryable and does not mark annual success',async()=>{const h=harness({outcome:'rejected'});await h.process({...h.row},settings);assert.equal(h.row.status,'failed');assert.equal(h.client.last_birthday_sent_year,null);});
test('ambiguous network failure is never automatically resent',async()=>{const h=harness({outcome:'timeout'});await h.process({...h.row},settings);assert.equal(h.row.status,'unknown');await h.process({...h.row},settings);assert.equal(h.calls,1);assert.equal(h.client.last_birthday_sent_year,null);});
test('Storage failure never reaches WhatsApp',async()=>{const h=harness({storageFailure:true});await h.process({...h.row},settings);assert.equal(h.calls,0);assert.equal(h.row.status,'failed');});
test('paused automation rejects a reserved birthday',async()=>{const h=harness();await h.process({...h.row},{...settings,automation_enabled:false});assert.equal(h.calls,0);assert.equal(h.row.status,'failed');});
