import {syncAndroidBirthdays,clearAndroidBirthdays} from './android-bridge.js';
import {createBirthdayAlerts} from './birthday-alerts.js';
import {bindManualDialog} from './manual.js';
import {createClient} from '@supabase/supabase-js';
import Papa from 'papaparse';
import {phoneE164,validBirthday,localDate,daysUntil} from './domain.js';
import {cardSvg,xml} from '../supabase/functions/_shared/card.js';
const $=s=>document.querySelector(s), app=$('#app');
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_ANON_KEY;
const configured=url&&key&&!url.includes('YOUR_PROJECT');
const db=configured?createClient(url,key):null;
let clients=[],messages=[],settings={},page='Dashboard',photo='',logo='';
const birthdayAlerts=createBirthdayAlerts({getState:()=>({clients,settings}),prepare:manualDialog,refresh:async()=>{clients=await allRows('clients');syncAndroidBirthdays(clients,settings);}});
const labels={sent:'Aceptado por Meta',failed:'Fallido',pending:'Pendiente',sending:'Enviando',unknown:'Revisar en Meta'};
const esc=xml;
function notice(text){$('#notice').textContent=text;setTimeout(()=>$('#notice').textContent='',6500);}
function check({data,error}){if(error)throw error;return data;}
async function run(fn){try{await fn();}catch(e){notice(e.message||'No se pudo completar la acción');}}
function field(label,name,value='',type='text',extra=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function checked(label,name,value){return `<label class="check"><input type="checkbox" name="${name}" ${value?'checked':''}>${label}</label>`;}
function status(m){return `<span class="badge ${m.status}">${labels[m.status]||esc(m.status)}</span>`;}
async function allRows(table){let rows=[],start=0;while(true){const chunk=check(await db.from(table).select('*').order(table==='clients'?'name':'created_at',{ascending:table==='clients'}).range(start,start+999));rows.push(...chunk);if(chunk.length<1000)return rows;start+=1000;}}
async function load(){[clients,messages,settings]=await Promise.all([allRows('clients'),allRows('birthday_messages'),db.from('business_settings').select('*').eq('id',1).single().then(check)]);for(const [path,target] of [[settings.photo_path,'photo'],[settings.logo_path,'logo']]){let value='';if(path)value=check(await db.storage.from('brand').createSignedUrl(path,3600)).signedUrl;if(target==='photo')photo=value;else logo=value;}syncAndroidBirthdays(clients,settings);}
function today(){return localDate(new Date(),settings.timezone||'America/Phoenix');}
function person(c,upcoming=false){const days=daysUntil(c.birthday,today());return `<div class="person"><span class="avatar">${esc(c.name.slice(0,1))}</span><div class="details"><strong>${esc(c.name)}</strong><small>${esc(c.phone)}</small></div><span class="badge">${upcoming?(days===1?'Mañana':`En ${days} días`):(c.whatsapp_consent?'Autorizado':'Sin consentimiento')}</span><button data-prepare="${c.id}">Preparar</button></div>`;}
function historyTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Fecha</th><th>Estado</th><th>Detalle</th><th></th></tr></thead><tbody>${rows.map(m=>`<tr><td><strong>${esc(m.client_name)}</strong><br><small>${esc(m.phone)}${m.kind==='test'?' · Prueba':''}</small></td><td>${new Date(m.created_at).toLocaleString('es',{timeZone:settings.timezone})}</td><td>${status(m)}</td><td>${esc(m.error_message||m.whatsapp_message_id||'—')}</td><td>${m.image_path?`<button data-image="${m.id}">Ver tarjeta</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Todavía no hay envíos registrados.</div>';}
function dashboard(){const date=today(),birthdays=clients.filter(c=>c.birthday.slice(5)===date.slice(5)),upcoming=clients.filter(c=>daysUntil(c.birthday,date)>0).sort((a,b)=>daysUntil(a.birthday,date)-daysUntil(b.birthday,date)).slice(0,5),sent=messages.filter(m=>m.kind==='birthday'&&m.status==='sent'&&localDate(new Date(m.sent_at),settings.timezone).slice(0,7)===date.slice(0,7));return `<div class="alert">Envío manual: prepara la tarjeta y completa el envío desde WhatsApp Business. Abrir un chat no confirma que se haya enviado.</div><div class="stats"><div class="stat">Cumpleaños de hoy<strong>${birthdays.length}</strong><small>${new Date(date+'T12:00:00').toLocaleDateString('es',{day:'numeric',month:'long'})}</small></div><div class="stat">Total de clientes<strong>${clients.length}</strong><small>${clients.filter(c=>c.active&&c.whatsapp_consent).length} activos y autorizados</small></div><div class="stat">Enviados este mes<strong>${sent.length}</strong><small>Aceptados por Meta</small></div><div class="stat">Mensajes fallidos<strong>${messages.filter(m=>m.status==='failed').length}</strong><small>${messages.filter(m=>m.status==='unknown').length} por revisar</small></div></div><div class="split"><section class="panel"><h2>Hoy celebramos</h2>${birthdays.map(c=>person(c)).join('')||'<div class="empty">Hoy no hay cumpleaños.<br>Las próximas celebraciones aparecerán aquí.</div>'}</section><section class="panel"><h2>Próximos cumpleaños</h2>${upcoming.map(c=>person(c,true)).join('')||'<div class="empty">Añade tu primer cliente para empezar.</div>'}</section></div><section class="panel"><div class="row"><h2>Últimos envíos</h2><button data-page="Historial">Ver historial</button></div>${historyTable(messages.slice(0,6))}</section>`;}
function clientRows(search=''){return clients.filter(c=>(c.name+' '+c.phone).toLowerCase().includes(search.toLowerCase())).map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.phone)}</td><td>${esc(c.birthday)}</td><td>${c.active?'Activo':'Pausado'} · ${c.whatsapp_consent?'Autorizado':'Sin consentimiento'}</td><td><div class="actions"><button data-edit="${c.id}">Editar</button><button data-toggle="${c.id}">${c.active?'Pausar':'Activar'}</button><button data-prepare="${c.id}" class="primary">Preparar felicitación</button><button data-delete="${c.id}">Eliminar</button></div></td></tr>`).join('')||'<tr><td colspan="5" class="empty">No hay clientes que mostrar.</td></tr>';}
function clientsView(){return `<section class="panel"><div class="toolbar"><input id="search" aria-label="Buscar clientes" placeholder="Buscar nombre o teléfono"><div class="actions"><button id="import">Importar CSV</button><button id="add" class="primary">+ Añadir cliente</button></div></div><div class="table-wrap"><table><thead><tr><th>Nombre</th><th>Teléfono</th><th>Cumpleaños</th><th>Permisos</th><th>Acciones</th></tr></thead><tbody id="clients-body">${clientRows()}</tbody></table></div></section>`;}
function design(){return `<div class="split"><section class="panel"><h2>Tu felicitación</h2><form id="design-form" class="form-grid"><label class="full">Texto principal<input name="greeting_text" maxlength="80" value="${esc(settings.greeting_text)}" required></label><p class="help full">Usa {{name}} para incluir el nombre del cliente. La fotografía y el logo pertenecen a tu negocio.</p><label class="full">Foto del propietario<input type="file" name="photo" accept="image/png,image/jpeg"></label><label class="full">Logo del negocio<input type="file" name="logo" accept="image/png,image/jpeg"></label><p class="help full">PNG o JPG, hasta 5 MB. Para la foto utiliza un retrato cuadrado.</p><button class="primary full">Guardar diseño</button></form></section><section class="panel"><h2>Vista previa</h2><label>Nombre de ejemplo<input id="example-name" value="Michael" maxlength="60"></label><p class="help">Composición aproximada. Usa «Vista previa de tarjeta» para descargar el PNG generado en el servidor.</p><div id="preview" class="preview-area"></div></section></div>`;}
function config(){return `<section class="panel"><h2>Configuración del negocio</h2><form id="settings-form" class="form-grid">${field('Nombre del negocio','business_name',settings.business_name,'text','required maxlength="60"')}${field('Persona que felicita','owner_name',settings.owner_name,'text','required maxlength="60"')}${field('Zona horaria','timezone',settings.timezone,'text','required')}${field('País para teléfonos sin prefijo (US, MX, ES…)','default_country',settings.default_country,'text','required maxlength="2" pattern="[A-Z]{2}"')}<label class="full">Mensaje para WhatsApp<textarea name="whatsapp_message" maxlength="1024" required>${esc(settings.whatsapp_message)}</textarea></label><p class="help full">Usa {{name}} para incluir el nombre del cliente. Podrás revisar el texto antes de abrir el chat. Envía desde WhatsApp Business con el número +1 480 504 9855.</p><div class="full"><button class="primary">Guardar configuración</button></div></form></section>`;}
function render(){const sections=['Dashboard','Clientes','Historial','Diseño de felicitación','Configuración'];app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><b>✳</b> Celebrar</div><nav>${sections.map((name,i)=>`<button data-page="${name}" class="${page===name?'active':''}"><span aria-hidden="true">${['◫','○','↗','◇','⚙'][i]}</span> &nbsp;${name}</button>`).join('')}</nav><footer>${esc(settings.business_name)}<br>Un detalle que conecta.<br><button id="logout">Cerrar sesión</button></footer></aside><main class="workspace"><header class="topbar"><div><div class="eyebrow">${esc(settings.business_name)}</div><h1>${page}</h1></div><div class="actions"><button id="refresh">Actualizar</button><button id="test" class="primary">Vista previa de tarjeta</button><button id="logout-mobile" aria-label="Cerrar sesión">Salir</button></div></header><div class="status-line">${esc(settings.timezone)} · Envío manual con WhatsApp Business</div><section id="birthday-alerts" aria-label="Avisos de cumpleaños"></section>${page==='Dashboard'?dashboard():page==='Clientes'?clientsView():page==='Historial'?`<section class="panel"><div class="toolbar"><h2>Todos los envíos</h2><select id="history-filter" aria-label="Filtrar estado" style="max-width:240px"><option value="">Todos los estados</option>${Object.entries(labels).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><p class="help">Este historial conserva los intentos anteriores de la API. Los envíos manuales se comprueban en WhatsApp Business; preparar una tarjeta o abrir un chat no crea un registro de envío.</p><div id="history-table">${historyTable(messages)}</div></section>`:page==='Diseño de felicitación'?design():config()}</main></div>`;bind();}
function bind(){birthdayAlerts.update();document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render();});$('#logout')?.addEventListener('click',logout);$('#logout-mobile').onclick=logout;$('#refresh').onclick=()=>run(async()=>{await load();render();});$('#test').onclick=()=>manualDialog();$('#add')?.addEventListener('click',()=>clientDialog());$('#search')?.addEventListener('input',e=>{$('#clients-body').innerHTML=clientRows(e.target.value);});$('#import')?.addEventListener('click',importDialog);$('#history-filter')?.addEventListener('change',e=>{$('#history-table').innerHTML=historyTable(messages.filter(m=>!e.target.value||m.status===e.target.value));});$('#settings-form')?.addEventListener('submit',e=>{e.preventDefault();run(async()=>{const form=new FormData(e.target),values=Object.fromEntries(form);values.automation_enabled=false;new Intl.DateTimeFormat('en',{timeZone:values.timezone});if(values.automation_enabled&&(!values.template_name||!settings.photo_path||!settings.logo_path))throw new Error('Configura la plantilla, la foto y el logo antes de activar');check(await db.from('business_settings').update(values).eq('id',1));await load();render();notice('Configuración guardada');});});$('#design-form')?.addEventListener('submit',e=>{e.preventDefault();run(async()=>{const form=new FormData(e.target),values={greeting_text:form.get('greeting_text')};for(const name of ['photo','logo']){const file=form.get(name);if(file.size){if(file.size>5242880||!['image/png','image/jpeg'].includes(file.type))throw new Error('Usa una imagen PNG/JPG de hasta 5 MB');const path=`${name}/${crypto.randomUUID()}.${file.type==='image/png'?'png':'jpg'}`;check(await db.storage.from('brand').upload(path,file));values[name+'_path']=path;}}check(await db.from('business_settings').update(values).eq('id',1));await load();render();notice('Diseño guardado');});});if($('#example-name')){const preview=()=>{$('#preview').innerHTML=cardSvg({...settings,greeting_text:$('#design-form [name=greeting_text]').value},$('#example-name').value,photo,logo).replace('<svg ','<svg class="card-preview" ');};$('#example-name').oninput=preview;$('#design-form [name=greeting_text]').oninput=preview;preview();}}
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;run(async()=>{if(b.dataset.edit)clientDialog(clients.find(c=>c.id===b.dataset.edit));if(b.dataset.toggle){const c=clients.find(c=>c.id===b.dataset.toggle);check(await db.from('clients').update({active:!c.active}).eq('id',c.id));await load();render();}if(b.dataset.delete){const c=clients.find(c=>c.id===b.dataset.delete);dialog(`<h2>Eliminar a ${esc(c.name)}</h2><p>Se eliminará el cliente. El historial y la protección anual de su teléfono se conservarán.</p><button class="primary" id="confirm-delete">Eliminar cliente</button>`);$('#confirm-delete').onclick=()=>run(async()=>{check(await db.from('clients').delete().eq('id',c.id));closeDialog();await load();render();});}if(b.dataset.prepare)manualDialog(clients.find(c=>c.id===b.dataset.prepare));if(b.dataset.retry){b.disabled=true;await action({action:'retry',id:b.dataset.retry});}if(b.dataset.image){const m=messages.find(m=>m.id===b.dataset.image),signed=check(await db.storage.from('birthday-cards').createSignedUrl(m.image_path,300));dialog(`<h2>Tarjeta enviada</h2><img class="card-preview" alt="Tarjeta de cumpleaños" src="${esc(signed.signedUrl)}">`);}});});
function dialog(html){document.querySelector('dialog')?.remove();const d=document.createElement('dialog');d.innerHTML=`<div class="row"><span></span><button id="close-dialog" aria-label="Cerrar">✕</button></div>${html}`;document.body.append(d);d.querySelector('#close-dialog').onclick=closeDialog;d.showModal();}
function closeDialog(){document.querySelector('dialog')?.close();document.querySelector('dialog')?.remove();}
function clientDialog(c={active:true,whatsapp_consent:false}){dialog(`<h2>${c.id?'Editar':'Añadir'} cliente</h2><form id="client-form">${field('Nombre','name',c.name||'','text','required maxlength="60"')}${field('Teléfono','phone',c.phone||'','tel','required')}${field('Cumpleaños','birthday',c.birthday||'','date','required')}${checked('Felicitaciones activas','active',c.active)}${checked('Autorizó recibir mensajes por WhatsApp','whatsapp_consent',c.whatsapp_consent)}${field('Referencia del consentimiento (fecha y origen)','consent_note',c.consent_note||'')}<button class="primary">Guardar cliente</button></form>`);$('#client-form').onsubmit=e=>{e.preventDefault();run(async()=>{const data=new FormData(e.target),values={name:data.get('name').trim(),phone:phoneE164(data.get('phone'),settings.default_country),birthday:validBirthday(data.get('birthday')),active:data.has('active'),whatsapp_consent:data.has('whatsapp_consent'),consent_note:data.get('consent_note')};check(await(c.id?db.from('clients').update(values).eq('id',c.id):db.from('clients').insert(values)));closeDialog();await load();render();notice('Cliente guardado');});};}
function manualDialog(c){
 dialog(`<h2>${c?'Preparar felicitación':'Vista previa de tarjeta'}</h2><p class="help">${c?esc(c.name)+' · '+esc(c.phone):'Genera una tarjeta de ejemplo sin enviar mensajes.'}</p><form>${field('Nombre en la tarjeta','name',c?.name||'Alex','text','required maxlength="60"')}<button class="primary">Generar tarjeta</button></form><p class="manual-status help" role="status" aria-live="polite"></p><div class="manual-result"></div>`);
 bindManualDialog(document.querySelector('dialog'),{client:c,settings,preview:async name=>{
  const {data:{session}}=await db.auth.getSession();if(!session)throw new Error('Vuelve a iniciar sesión.');
  const response=await fetch(url+'/functions/v1/admin-action',{method:'POST',headers:{Authorization:'Bearer '+session.access_token,apikey:key,'Content-Type':'application/json'},body:JSON.stringify({action:'preview',name})});
  if(!response.ok){const result=await response.json();throw new Error(result.error||result.message||'No se pudo generar la tarjeta.');}return response.blob();
 }});
}
async function action(body){const result=check(await db.functions.invoke('admin-action',{body}));if(result.error)throw new Error(result.error);await load();render();notice(result.message?`${labels[result.message.status]}${result.message.error_message?': '+result.message.error_message:''}`:'Acción completada');}
function importDialog(){dialog(`<h2>Importar clientes</h2><p class="help">CSV UTF-8 con columnas <b>name, phone, birthday, active, whatsapp_consent, consent_note</b>. Fechas YYYY-MM-DD; booleanos true/false. Los teléfonos existentes se omiten. Para Excel, guarda como CSV UTF-8.</p><a href="./clients-example.csv" download>Descargar ejemplo CSV</a><label>Archivo CSV<input id="csv-file" type="file" accept=".csv,text/csv"></label><div id="import-result" class="help"></div><button id="commit-import" class="primary" disabled>Importar válidos</button>`);let rows=[];$('#csv-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>5*1024*1024){notice('Máximo 5 MB por CSV');return;}const parsed=Papa.parse(await file.text(),{header:true,skipEmptyLines:'greedy',transformHeader:h=>h.trim().replace(/^\uFEFF/,'')});const errors=parsed.errors.map(e=>e.message),seen=new Set(clients.map(c=>c.phone));rows=[];parsed.data.forEach((r,i)=>{try{if(!r.name?.trim()||r.name.trim().length>60)throw new Error('Nombre requerido (máximo 60)');const phone=phoneE164(r.phone,settings.default_country);if(seen.has(phone))throw new Error('Teléfono duplicado; omitido');const boolean=(v,fallback)=>{if(v===undefined||v==='')return fallback;if(!['true','false'].includes(v.trim().toLowerCase()))throw new Error('Usa true/false en permisos');return v.trim().toLowerCase()==='true';};rows.push({name:r.name.trim(),phone,birthday:validBirthday(r.birthday?.trim()),active:boolean(r.active,true),whatsapp_consent:boolean(r.whatsapp_consent,false),consent_note:r.consent_note||''});seen.add(phone);}catch(err){errors.push(`Fila ${i+2}: ${err.message}`);}});$('#import-result').textContent=`${rows.length} clientes válidos. ${errors.length} incidencias.\n${errors.slice(0,15).join('\n')}`;$('#import-result').style.whiteSpace='pre-wrap';$('#commit-import').disabled=!rows.length;};$('#commit-import').onclick=()=>run(async()=>{const button=$('#commit-import');button.disabled=true;let saved=0;try{while(rows.length){const batch=rows.slice(0,200);check(await db.from('clients').insert(batch));rows.splice(0,batch.length);saved+=batch.length;}closeDialog();await load();render();notice(`${saved} clientes importados`);}catch(e){await load();button.disabled=false;throw new Error(`${saved} importados. ${rows.length} pendientes. ${e.message}`);}});}
async function logout(){birthdayAlerts.stop();check(await db.auth.signOut());clearAndroidBirthdays();clients=[];messages=[];settings={};login();}
function login(){birthdayAlerts.stop();app.innerHTML=`<section class="login panel"><div class="brand"><b>✳</b> Celebrar</div><h1>Tu panel de cumpleaños</h1><p class="help">Introduce tu código de acceso.</p><form id="login-form"><label>Código de 4 dígitos<input name="pin" type="password" inputmode="numeric" pattern="[0-9]{4}" minlength="4" maxlength="4" required autocomplete="off" autofocus></label><button class="primary">Entrar al panel</button></form><p class="help">Acceso exclusivo para el administrador.</p></section>`;$('#login-form').onsubmit=e=>{e.preventDefault();const form=e.target;run(async()=>{const button=form.querySelector('button');button.disabled=true;try{const response=await fetch(url+'/functions/v1/pin-login',{method:'POST',headers:{'Content-Type':'application/json',apikey:key},body:JSON.stringify({pin:new FormData(form).get('pin')})});const result=await response.json();if(!response.ok)throw new Error(result.error||'No se pudo iniciar sesión');check(await db.auth.setSession({access_token:result.access_token,refresh_token:result.refresh_token}));await enter();}finally{if(button.isConnected)button.disabled=false;}});};}
async function enter(){const {data:{session}}=await db.auth.getSession();if(!session)return login();const admin=check(await db.from('admin_user').select('user_id').maybeSingle());if(!admin){await db.auth.signOut();login();throw new Error('Esta cuenta no es el administrador autorizado');}await load();render();}
if(!configured){app.innerHTML='<section class="setup panel"><div class="brand"><b>✳</b> Celebrar</div><h1>Conecta tu negocio</h1><p>El panel está preparado. Falta configurar la conexión con Supabase para iniciar sesión y gestionar tus clientes.</p><p>Configura <code>VITE_SUPABASE_URL</code> y <code>VITE_SUPABASE_ANON_KEY</code> en el archivo <code>.env</code>, siguiendo el README del proyecto.</p><p class="help">Las credenciales privadas de WhatsApp se configuran únicamente en el backend.</p></section>';}else{run(enter);db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')login();});}
