project_id = "birthday-whatsapp"
[functions.birthday-cron]
verify_jwt = false
static_files = ["./functions/_shared/assets/*"]
[functions.admin-action]
verify_jwt = false
static_files = ["./functions/_shared/assets/*"]
